version: '3'
services:
  base:
    image: node:alpine
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: 
      - /bin/sh
      - -c
      - |
        npm i
        npx parcel index.html
    ports:
    - 1234:1234
